### ISSUE TITLE
local not used in a function

### ISSUE THREAD

**Issue by demizer** [graysky2/clean-chroot-manager#10]
# ccm64 u

    /usr/bin/ccm64: line 44: local: can only be used in a function
    ==> ERROR:

logname does not work in tmux for some reason. I get:

    logname: no login name

Not sure why. The script works fine out of tmux.

**Comment by thiagowfx** [comment]
I just installed your package and was going to open a new issue but I found this one. I have the very same problem (except that I don't use tmux):

    thiago@archpad ~ % echo $SHELL
    /usr/bin/zsh
    thiago@archpad ~ % echo $TERM
    rxvt-unicode-256color

logname from a tty works, but logname from urxvt using zsh don't:

    thiago@archpad ~ % logname
    logname: no login name

I won't mess up with setuid since it could cause security issues.
The quick and dirty solution for me is to manually remove/change `logname` from /usr/bin/ccm*. But er....it is dirty.

Do you plan to change that in the future? Some alternatives include:

    whoami
    id -un
    $USER

You could, for example, add a second method in the case that `logname` fails (instead of removing `logname`).

**Comment by graysky2** [comment]
Under now, I haven't been able to find an alternative to `logname` that will return the user name when called via sudo.

In my testing on urxvt and tmux:
`sudo id -in` returns: root
`sudo whoami` returns: root

Problem is that a user calls the script via sudo, the $USER from the shell becomes root so nothing works.

After some googling, it seems as though $SUDO_USER might provide to be a good solution.  I will test a bit and then release a version that implements this when logname fails.

FYI - The solution for `logname` to work for tmux is an in-tree patch: https://bugs.archlinux.org/task/43368

**Comment by graysky2** [comment]
https://github.com/graysky2/clean-chroot-manager/compare/v2.62...v2.63

Thanks for the suggestion!

**Comment by thiagowfx** [comment]
Thanks, this patch works for me!

**Comment by graysky2** [comment]
Glad to hear it.  No need to patch: https://aur.archlinux.org/packages/clean-chroot-manager/
