### ISSUE TITLE
cores+1=increased compile time

### ISSUE THREAD

**Issue by wifiextender** [graysky2/clean-chroot-manager#17]
Hello graysky,

I've been extensively using clean-chroot, but saw that you've added [cores+1](https://github.com/graysky2/clean-chroot-manager/blob/master/common/clean-chroot-manager64.in#L82) recently which increases the compile time.

My processor have 3 cores, no HT. Those having X cores and X threads will benefit from higher cores++, but the rest like me will not. Compiled vim from abs 6 times to prove it.

```bash

for x in {1..6}; do cp -r /var/abs/extra/vim /tmp; cd /tmp/vim; sed -i "s/-j1/-j${x}/g" PKGBUILD; time makepkg --syncdeps; sudo rm -rf /tmp/vim; scrot --focused "${HOME}/scrot-${x}.png"; sudo sysctl --write vm.drop_caches=3;done

```

Compile time:

1 core. 10m43s , cpu load 33%
2 cores. 6m56s, cpu load 68%
3 cores. 5m38s, cpu load 100%
4. 5m40s
5. 5m42s
6. 5m44s

Cheers

**Comment by graysky2** [comment]
I tested this on my i7-3970k with and without HT enabled and found a similar trend.  Interestingly, the old cores+1 rule holds true on this HT chip, but does show a slight decrease when HT is disabled as you say.  I guess I would recommend that you make this change in your own package since I believe most modern chips do ship with HT options.  Below are the data I generated.

![ht_enabled](https://cloud.githubusercontent.com/assets/534822/9125176/db284ac8-3c6b-11e5-8b96-7e55e4a5fb9d.png)

![ht_disabled](https://cloud.githubusercontent.com/assets/534822/9125177/dfd12ffe-3c6b-11e5-9479-f198d9cb9e44.png)

Here is the simple script I used to generate these data: https://github.com/graysky2/bin/blob/master/bench-threads

**Comment by wifiextender** [comment]
Hello graysky,

Thanks for the reply and script.

Saw that you've been using [cpuz](https://github.com/graysky2/bin/blob/master/cpuz) script, if you don't mind you can use my dwm [statusbar](https://github.com/wifiextender/dwm-bar) program instead.

Cheers

**Comment by graysky2** [comment]
I haven't used that script in ages... (2012 by the date on it).  These days, I just use the simple xfce4 plugin for cores.
