### ISSUE TITLE
Build multiple PKGBUILDs without cleaning chroot

### ISSUE THREAD

**Issue by sdht0** [graysky2/clean-chroot-manager#4]
Hi,

When building PKGBUILDs of the same group (eg telepathy-kde for me), I would prefer to not clean the chroot before building because they have lot of common dependencies, and take a lot of additional time to install for each package.

I optionally disabled the -c option to makechrootpkg, but in that case the local repo in the working copy does not get updated. So then I added commands to manually update the working copy repo in case -c is disabled.

The above way feels a bit of a hack. I was wondering if you can think of a better way to optionally disable clean chroot option to makechrootpkg.

My way currently: https://github.com/siddharthasahu/clean-chroot-manager/commit/c65454c23864cef22aca7d687e1e77c2ea37f0f2

Thanks

**Comment by siddharthasahu** [comment]
Hi graysky. So I started using ccm again yesterday. Found some improvements you could make.

*) You added the 'do not clean chroot before build' option, but if I use that, packages built in the previous execution will not be available in the local repo, because it would not have synced from the root chroot.

*) By default, all build output files and logs are dumped in the PKGBUILD folder. I prefer to keep that folder clean, so I use environment variables to separate them to separate folders. That means the logic for adding built packages to local repo needs to be modified a bit (they are not present in pwd anymore).

One way of fixing the above: https://github.com/siddharthasahu/clean-chroot-manager/commits/features.

Also, I was wondering why you prefer keeping redudant code over using if-else. Keeping only one file for example will make it easier to add features to both 64 and 32 bit versions, no? Just curious how you think about this. :)
