### ISSUE TITLE
allow adding packages to chroot via `ccm` (as `mkarchroot` does)

### ISSUE THREAD

**Issue by rpuntaie** [graysky2/clean-chroot-manager#64]
... continuing from the topic hijacking in #63

Just had `Cannot find the git package needed to handle git sources`.
Could `pkgs` in `create()` take up also additional parameters ($@ after shift), to install packages like git in chroot?

Many AUR packages don't take the rule serious to include make dependencies not in base-devel to `makedepends`. One needs to add them manually. Anyway, `mkarchroot` allows to add packages to chroot, so I don't see why this shouldn't be forwarded via `ccm`. It is no big deal for me, just a suggestion.

For now one can add packages to chroot with, e.g.:

```
sudo pacstrap /scratch/.chroot64/root git unzip
```

**Comment by graysky2** [comment]
Since **arch-install-scripts** is a dependency of **devtools**, `pacstrap` is already on the system.  Could be possible to add a new target to allow this.  Something like adding a "i" option for install, eg `ccm i foo bar` but without playing with it, I am not sure how to handle multiple tokens and we would have to write something for error checking that the package(s) are real and exist.

**Comment by rpuntaie** [comment]
The `create` function, which calls `mkarchroot`, is called for `c`, `cd`, `s` and `S`.

AFAIK these commands don't use any further arguments.
I thought of forwarding additional parameters to `mkarchroot`.
(`shift` before the line with the `create` and in the `create` function, in the `mkarchroot` line, add the `$@` as parameter at the end.)
`mkarchroot` cares for errors if the package name are not OK.

**Comment by graysky2** [comment]
I'm thinking incorporating this would be a bit beyond the scope of the project.  As you pointed out, users can just call `pacstrap` to hit the buildroot directly; seems a bit superfluous to code it up in the wrapper.
